### ISSUE TITLE
error upgrading last version

### ISSUE THREAD

**Issue by nunoguerreiro** [PoetOS/moodle-mod_questionnaire#289] opened 2020-05-16 12:07 UTC
There is a new version 2020011506 available!
Release 3.8.1 (Build - 2020051500) Stable version 

Debug info: ERROR: syntax error at or near "TYPEid"
LINE 2: ...E mdl_questionnaire_response_bool ALTER COLUMN id TYPEid BIG...
^
BEGIN ISOLATION LEVEL SERIALIZABLE;
ALTER TABLE mdl_questionnaire_response_bool ALTER COLUMN id TYPEid BIGSERIAL
; COMMIT
Error code: ddlexecuteerror
×Stack trace:
line 492 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
line 259 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 688 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 77 of /lib/ddl/database_manager.php: call to pgsql_native_moodle_database->change_database_structure()
line 597 of /lib/ddl/database_manager.php: call to database_manager->execute_sql_arr()
line 901 of /mod/questionnaire/db/upgrade.php: call to database_manager->change_field_type()
line 826 of /lib/upgradelib.php: call to xmldb_questionnaire_upgrade()
line 532 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1877 of /lib/upgradelib.php: call to upgrade_plugins()
line 711 of /admin/index.php: call to upgrade_noncore()

**Comment by mwehr** [comment] 2020-05-16 13:58
It seems the problem is that in PostgreSQL you cannot easily change BIGINT to SERIAL 
See -> [Link](https://stackoverflow.com/questions/31965506/postgresql-column-type-conversion-from-bigint-to-bigserial)

**Comment by roessling** [comment] 2020-05-19 06:19
Not only that, the SQL syntax created above is also wonky IMHO.
ALTER TABLE _name_ ALTER COLUMN _column-name_ TYPE **_column_name_** _type_ is not correct, the "id" - especially clinging to "TYPE" as above - is illegal if I remember my SQL correctly.

**Comment by mchurchward** [comment] 2020-05-20 19:01
This was also reported in https://tracker.moodle.org/browse/CONTRIB-8096. I believe there is an issue in the core API to change the 'id' field length.

**Comment by mchurchward** [comment] 2020-05-21 20:30
I have [committed a change](https://github.com/PoetOS/moodle-mod_questionnaire/commit/fc733f637742f947f69ef28e83d60e6c7dae6dbc) that skips those field updates for Postgres - I don't think Postgres needs them anyway.
Can any of you test this and let me know how it gies?

**Comment by izendegi** [comment] 2020-05-22 06:05
Hi Mike,

I've tested that commit and it worked for me (Moodle 3.8.3 & PG 10.12), now it doesn't throw any error while upgrading.

**Comment by mwehr** [comment] 2020-05-22 08:06
Hi Mike,

Upgrade works as expected .

**Comment by mchurchward** [comment] 2020-05-22 13:00
Thanks for the confirmation. I have tagged and released 3.8.2 with this fix.

**Closed by mchurchward** 2020-05-22 13:00 UTC
