### ISSUE TITLE
Changing a dependency may not lead to corrected page breaks

### ISSUE THREAD

**Issue by kyro46** [PoetOS/moodle-mod_questionnaire#78] opened 2017-03-15 14:02 UTC
Hi, here an example:

Create a qs with 4 questions. 
1 (yes/no)
2
3 -> depends on 1->yes
4 -> depends on 1->yes

A page break will be created between 2 and 3.
Change the dependency of 4 to 1->no.
A page break will be created between 3 and 4.

Change the dependency of 4 back to 1->yes.

-> The page break between 4 and 3 will stay and will remain uneditable despite both questions sharing the same dependency again.

Tested with MOODLE_32_STABLE.

**Comment by mchurchward** [comment] 2017-03-15 18:11
Just testing to duplicate results.
You said, "A page break will be created between 2 and 3." I don't see this. I see Q1 -> Page break -> Q2, Q3.
(see image):
![screen shot 2017-03-15 at 2 06 39 pm](https://cloud.githubusercontent.com/assets/819054/23963735/a665f178-0988-11e7-913f-90810023d6ce.png)

I'm guessing you meant between question 1 and 2, right?

Anyway, yes, I see that the page break remains. I can get rid of it by deleting question 3. I'm not sure it even makes sense to allow the same conditional on a consecutive question, does it? In any case, I will look and see what is going on there.

**Comment by mchurchward** [comment] 2017-03-15 18:27
Okay... So according to the docs, you group questions together on one page by making them consecutive and giving them the same parent. Now I see. So the problem is that once they have been broken apart, they can no longer be regrouped.

**Comment by mchurchward** [comment] 2017-03-15 18:31
It looks like you need to move the question back into the "yes" group. So, once you change Q3 from depending on "no" to depending on "yes" again, the page break remains. If you then move Q3 to before that page break, the page break is removed.

**Comment by mchurchward** [comment] 2018-01-30 16:47
There has been a lot of new work around dependent questions in the new 3.4 release, including the ability to have multiple dependent questions. I'm going to close this issue. If you still see a problem with the new feature, please feel free to reopen.

**Closed by mchurchward** 2018-01-30 16:47 UTC
