### ISSUE TITLE
Incorrect response data when using Rate(Scale) question type

### ISSUE THREAD

**Issue by yexiangwu** [PoetOS/moodle-mod_questionnaire#233] opened 2019-10-23 09:16 UTC
Hi,

One of our school teacher told me that the questionnaire responses data is changed and become wrong after we updated yesterday. They are using Rate questions to vote, and they used this way for several years. I found that the data is totally messed up:

I created a new test questionnaire with one rate question, the same problem occurs when I try to look at the response:

The original rate record:
![Screen Shot 2019-10-23 at 16 50 58](https://user-images.githubusercontent.com/56913852/67375577-6b530780-f5b5-11e9-9dba-561fd723cb7f.png)

and the summary data:
![Screen Shot 2019-10-23 at 16 50 47](https://user-images.githubusercontent.com/56913852/67375652-845bb880-f5b5-11e9-950e-3167bd7a8495.png)

These two report doesn't match.

When I try to download the excel file, the data is wrong, too:
![Screen Shot 2019-10-23 at 16 56 49](https://user-images.githubusercontent.com/56913852/67376085-1ebbfc00-f5b6-11e9-8f1a-fcb8ca58073d.png)

For the teacher's issue, all the first choice is missed and other data is wrong too:
![Screen Shot 2019-10-23 at 11 54 21](https://user-images.githubusercontent.com/56913852/67377667-9e4aca80-f5b8-11e9-86d5-a4a3c9d30eba.png)

Could you please help investigate the problem ???

**Comment by anatolyg7** [comment] 2019-10-23 19:24
Another related problem is rate question with N/A column - now you can't select N/A (can't save n/a selection) - seems that the problem with display affects what is saved in the database. When you select n/a and submit - you get an error "something's wrong with your question"

**Comment by anatolyg7** [comment] 2019-10-25 12:46
quickly fixed this by editing query in file classes/responsetype/rank.php in function get_results to be this

 (SELECT c2.id, AVG(a2.rankvalue) AS average, COUNT(a2.response_id) AS num
                          FROM {questionnaire_quest_choice} c2, {".static::response_table()."} a2
                          WHERE c2.question_id = ? AND a2.question_id = ? AND a2.choice_id = c2.id AND a2.rankvalue >= 0{$rsql}
                          GROUP BY c2.id) a ON a.id = c.id
                          order by c.id";


and in file classes/responsetype/display_support.php in function mkrescount
change selected in bold

       $nbranks = $length;
        $ranks = array();
        foreach ($rows as $row) {
            $choiceid = $row->id;
            foreach ($choices as $choice) {
                if ($choice->choiceid == $choiceid) {
                    $n = 0;
                    for ($i = 0; $i < $nbranks; $i++) {
                        if ($choice->rankvalue == $i**+1**) {

**Comment by yexiangwu** [comment] 2019-10-28 05:39
> quickly fixed this by editing query in file classes/responsetype/rank.php in function get_results to be this
> 
> (SELECT c2.id, AVG(a2.rankvalue) AS average, COUNT(a2.response_id) AS num
> FROM {questionnaire_quest_choice} c2, {".static::response_table()."} a2
> WHERE c2.question_id = ? AND a2.question_id = ? AND a2.choice_id = c2.id AND a2.rankvalue >= 0{$rsql}
> GROUP BY c2.id) a ON a.id = c.id
> order by c.id";
> 
> and in file classes/responsetype/display_support.php in function mkrescount
> add +1 in the last line below (selected with **)
> 
> ```
>    $nbranks = $length;
>     $ranks = array();
>     foreach ($rows as $row) {
>         $choiceid = $row->id;
>         foreach ($choices as $choice) {
>             if ($choice->choiceid == $choiceid) {
>                 $n = 0;
>                 for ($i = 0; $i < $nbranks; $i++) {
>                     if ($choice->rankvalue == $i**+1**) {
> ```

### Thank you so much. We tried it today, the summary data looks fine now. However, the downloaded data in excel is still wrong. Do you have any ideas on solving this problem?

**Comment by anatolyg7** [comment] 2019-10-28 10:38
It should be an easy fix - just find the procedure that prepares csv and implement the same fix (add or substract 1 from the value when it is generated)

**Comment by mchurchward** [comment] 2019-11-05 19:44
What version of questionnaire is this? And are you using named degrees?

**Comment by anatolyg7** [comment] 2019-11-05 21:16
it started on version 3.7. And error exists both for usual rate questions and for named degrees. I think the error comes from change in the way rate values are stored - it was 0 to n-1 (n- number of points in rate scale), in 3.7 it is changed to 1..n. And there are several places left in code where it is still supposed that the values are stored 0..n-1 (csv export, summary results display)

**Comment by mchurchward** [comment] 2019-11-05 21:20
Yep. I'm seeing it now. There were a number of changes done that impact Rate questions. Named degrees storing was one. But this complaint is caused by attempting to standardize how rate values were used. The code always used "1-5", while the data stored was "0-4". Looks like I missed some uses.
Also note #239 which is somewhat related.

**Comment by mchurchward** [comment] 2019-11-05 21:22
> Another related problem is rate question with N/A column - now you can't select N/A (can't save n/a selection) - seems that the problem with display affects what is saved in the database. When you select n/a and submit - you get an error "something's wrong with your question"

I can't see this problem. This does not happen for me. Can you outline the exact settings for a question with this problem?

**Comment by mchurchward** [comment] 2019-11-05 21:27
If the N/A column is indeed a problem, can you open a new issue for it, outlining how to duplicate it? Thanks.

**Comment by mchurchward** [comment] 2019-11-05 21:30
Fixed with commit cebe80b

**Closed by mchurchward** 2019-11-05 21:30 UTC

**Comment by anatolyg7** [comment] 2019-11-06 09:01
Seems that N/A problem was a different one - possibly a user problem. Will report it as a separate issue

**Comment by camiernes** [comment] 2019-11-07 20:24
> 
> 
> > quickly fixed this by editing query in file classes/responsetype/rank.php in function get_results to be this
> > (SELECT c2.id, AVG(a2.rankvalue) AS average, COUNT(a2.response_id) AS num
> > FROM {questionnaire_quest_choice} c2, {".static::response_table()."} a2
> > WHERE c2.question_id = ? AND a2.question_id = ? AND a2.choice_id = c2.id AND a2.rankvalue >= 0{$rsql}
> > GROUP BY c2.id) a ON a.id = c.id
> > order by c.id";
> > and in file classes/responsetype/display_support.php in function mkrescount
> > add +1 in the last line below (selected with **)
> > ```
> >    $nbranks = $length;
> >     $ranks = array();
> >     foreach ($rows as $row) {
> >         $choiceid = $row->id;
> >         foreach ($choices as $choice) {
> >             if ($choice->choiceid == $choiceid) {
> >                 $n = 0;
> >                 for ($i = 0; $i < $nbranks; $i++) {
> >                     if ($choice->rankvalue == $i**+1**) {
> > ```
> 
> ### Thank you so much. We tried it today, the summary data looks fine now. However, the downloaded data in excel is still wrong. Do you have any ideas on solving this problem?

Hello yexiangwu, I had the same error when I downloaded excel data and searching a litle bit and found it in the file mod/questionnaire/questionnaire.class.php in specific code line number 3086 inside of generate_csv function
...
3082        if ($qtype === QUESRATE || $qtype === QUESCHECK) {
3083                $key = $qid.'_'.$responserow->choice_id;
3084                $position = $questionpositions[$key];
3085                if ($qtype === QUESRATE) {
3086                    //$choicetxt = $responserow->rankvalue + 1;
                            $choicetxt = $responserow->rankvalue;
                       } else {
