### ISSUE TITLE
Question in date format can't filled in

### ISSUE THREAD

**Issue by ralf-krause** [PoetOS/moodle-mod_questionnaire#288] opened 2020-05-10 16:51 UTC
We have a questionnaire with a question in date format but we can't fill in a date.

<img width="766" alt="moodle-questionnaire-date-1" src="https://user-images.githubusercontent.com/27956839/81505380-12e41d00-92ef-11ea-80fa-274bf5c4375d.png">

**Comment by ralf-krause** [comment] 2020-05-10 16:59
I tested to enter the date in the correct german format. This seems to be better. Question #1 is accepted without an error message but only a zero is shown in the date field.

<img width="772" alt="moodle-questionnaire-date-2" src="https://user-images.githubusercontent.com/27956839/81505536-3cea0f00-92f0-11ea-9a30-95c2dc5c296b.png">

<img width="797" alt="moodle-questionnaire-date-3" src="https://user-images.githubusercontent.com/27956839/81505545-45dae080-92f0-11ea-86c7-f98dadda5819.png">

**Comment by ralf-krause** [comment] 2020-05-10 17:07
All three pictures above are made with the Safari browser on a Mac. Now I tested the same with the Chrome browser. The Chrome browser shows a calendar when clicking into the date input field. But the result is also the german date format.

<img width="760" alt="moodle-questionnaire-date-4" src="https://user-images.githubusercontent.com/27956839/81505692-6bb4b500-92f1-11ea-8dd2-2c84340f9190.png">

**Comment by mchurchward** [comment] 2020-05-14 18:45
What version and release of questionnaire are you using?
As of release 3.6.1, the date input was modified to use the HTML5 date selector by default, and require text entry in the YYYY-MM-DD format if the browser doesn't support HTML5 date selector (Safari doesn't). It should allow you to enter the date in that format.

**Comment by ralf-krause** [comment] 2020-05-15 08:13
I am using Moodle 3.8.3 and the current questionnaire version 3.7.4 (Build - 2020011300).

**Comment by ralf-krause** [comment] 2020-05-15 08:25
The following screenshots are showing a questionnaire with a date field. I used the Chrome browser to test the input.

<img width="599" alt="Bildschirmfoto 2020-05-15 um 10 17 46" src="https://user-images.githubusercontent.com/27956839/82028393-dcfbbb80-9695-11ea-8467-9650bc423999.png">

<img width="621" alt="Bildschirmfoto 2020-05-15 um 10 18 05" src="https://user-images.githubusercontent.com/27956839/82028602-2946fb80-9696-11ea-872c-5c5f4dd798c1.png">

<img width="620" alt="Bildschirmfoto 2020-05-15 um 10 18 18" src="https://user-images.githubusercontent.com/27956839/82028436-ebe26e00-9695-11ea-8720-a722fbfd2122.png">

<img width="683" alt="Bildschirmfoto 2020-05-15 um 10 19 09" src="https://user-images.githubusercontent.com/27956839/82028484-fef53e00-9695-11ea-91b8-1706224642f6.png">

**Comment by mchurchward** [comment] 2020-05-15 19:27
Hmmm... So the date selector entered the date in the 'DD.MM.YYYY' format? Is that correct?
There must be something in browsers that determines what format the date comes in....

**Comment by mchurchward** [comment] 2020-05-15 20:16
No... The display is supposed to localized. But the data format is supposed to be in a consistent format as 2020-05-15, which it is. This is odd.
I just made some changes in the MOODLE_38_STABLE release around the date processing. This has been released as 3.8.1. Can you try this release?

**Comment by ralf-krause** [comment] 2020-05-16 07:46
I can't update.

<img width="700" alt="Bildschirmfoto 2020-05-15 um 10 16 30" src="https://user-images.githubusercontent.com/27956839/82113966-18f85480-975a-11ea-9c41-fddcda947645.png">

**Comment by rlorenzo** [comment] 2020-05-20 21:17
We are also running Questionnaire 3.7.4 but on Moodle master and running into the same issue. But with the correct date being mm/dd/yyyy format instead of the example yyyy-mm-dd.

I checked out the MOODLE_38_STABLE branch and don't see any recent commits related to the date selector being fixed: https://github.com/PoetOS/moodle-mod_questionnaire/commits/MOODLE_38_STABLE

What commit is suppose to fix this? We can try the patch.

**Comment by mchurchward** [comment] 2020-05-20 22:11
Its the most recent commit: https://github.com/PoetOS/moodle-mod_questionnaire/commit/28c4c1c03d5d89d9de23f49f0a4d5d488f1ead20
And I don't know if it fixes the problem - I can't replicate it. It almost seems like the date selector doesn't work like it specified to.

**Comment by mchurchward** [comment] 2020-05-22 12:50
@rlorenzo did that commit work for you?

**Comment by ralf-krause** [comment] 2020-05-24 12:55
@mchurchward 
Hi Mike, I installed the questionnaire plugin once more and now I had no installation problem with the version 3.8.2 of your plugin. Great thing. My Moodle ist 3.8.3+ (Build: 20200512).

But there are some problems with the handling of the date field. The date format depends on the user language in Moodle. I tried to browsers: Safari and Chrome on macOS. 

With Chrome I get an assistance for my date entry. The small calendar is the same in english and in german language. The entry format is tt.mm.jjjj .... I am using the german version of the Chrome browser. 
<img width="595" alt="moodle-questionnaire-chrome-en" src="https://user-images.githubusercontent.com/27956839/82753963-29e43e00-9dca-11ea-9904-0490e22aa7b5.png">

With Safari there is no assistance to enter the date. Typing in 2020-05-24 is accepted and 24.05.2020 is not accepted in Safari.
<img width="610" alt="moodle-questionnaire-chrome-de" src="https://user-images.githubusercontent.com/27956839/82754217-ceb34b00-9dcb-11ea-98b8-8e2c382f761f.png">

After testing the input options for the date field I looked at the export file. I downloaded two versions of the export file. First I switched Moodle to german language and downloaded the ods export file. Second I switched to english language a did the same. Please look at the screenshot to see the differences .... the column B "submitted on" shows the german and the english date format. The column J "Q01" shows the entries in the date field. In Chrome browser I must enter the german formatted string 24.05.2020 and I get an english formatted string in the export file.
<img width="1404" alt="moodle-questionnaire" src="https://user-images.githubusercontent.com/27956839/82754361-b5f76500-9dcc-11ea-8a21-5f0fbdf44f88.png">

I think that the users will have problems when they must fill in different formatted strings in different browsers.

Best regards, Ralf

**Comment by rlorenzo** [comment] 2020-05-26 21:28
@mchurchward We just updated to the latest version 3.8.2 (Build - 2020052100) and still have the same date issue.

![8f687cae-63a2-4660-8c1f-5d8dce8b5ddc](https://user-images.githubusercontent.com/349765/82952026-19b09800-9f5d-11ea-8254-94144c87a773.png)

**Comment by mchurchward** [comment] 2020-05-28 13:23
@rlorenzo can you provide more details please?
What browser / OS are you using?
What error do you get when you submit?
Is this using an HTML5 date selector or inputting manually?

**Comment by rlorenzo** [comment] 2020-05-28 17:50
@mchurchward Mac Catalina 10.15.5. Chrome 83.0.4103.61

I used Preview and it appears to accept the date. But this is going to be super confusing for students filling out the questionnaire if they are reading the instructions.

<img width="586" alt="Screen Shot 2020-05-28 at 10 49 48 AM" src="https://user-images.githubusercontent.com/349765/83175661-15a58700-a0d1-11ea-8b2a-c9950cee3116.png">

**Comment by rlorenzo** [comment] 2020-05-28 18:17
As a solution, can the instructions just be removed? Or just say "Use the date picker below".

Then to fix @ralf-krause issue with the date export differing, can the date then be converted to a unix timestamp once accepted by the user and then normalized to the YYY-MM-DD format? So the result is the same no matter what browser a user is using?

**Comment by rlorenzo** [comment] 2020-05-28 18:22
@mchurchward Actually I checked the support table for the date element https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Browser_compatibility and it does not work with Safari. I confirmed with the latest Safari 13.1.1.

Can the date question either be rolled back to the version that does not use date element or can this use Moodle's date selector? https://docs.moodle.org/dev/lib/formslib.php_Form_Definition#date_selector

**Comment by mchurchward** [comment] 2020-05-28 20:16
Correct. You can use the picker with Safari. But you should be able to type the date into the selector with the specified format.
Can you describe exactly what is happening when you are having problems?

**Comment by mchurchward** [comment] 2020-05-28 20:17
When I read how the HTML5 date picker is supposed to work, it says the display format may differ from browser and location, but the transferred format should always be 'YYYY-MM-DD'. So is the only problem the message string?

**Comment by rlorenzo** [comment] 2020-05-28 20:23
@mchurchward Yeah, the issue is that the instructions say to enter in the date using the 'YYYY-MM-DD' format, but the date field is not. that format depending on their browser/language. So it tripped up our testers and confused enough people that I had to look into it and found this issue.

If the date is always being returned as 'YYYY-MM-DD', then maybe the instructions can be changed to:

_Enter date using the date picker below, or if not available, enter in a date in 'YYYY-MM-DD' format._

Or can you detect the type of browser and it will use the current wording if it does not support the date element. Else it will just say:

_Enter date using the date picker below_

**Comment by mchurchward** [comment] 2020-06-26 15:04
Okay. Fixed in latest MOODLE_39_STABLE branch. There were two issues. The main one was that existing responses were being reformatted into the site's date format when displayed, which would cause problems if a response was being saved and restarted, or using a previous page click. The second was the misleading prompt. Now fixed.

**Closed by mchurchward** 2020-06-26 15:04 UTC

**Comment by ralf-krause** [comment] 2020-06-27 08:22
We are using Moodle 3.9 and we updated mod_questionnaire up to MOODLE_39_STABLE.

The date format is working well. Thank you very much. But the german translation for the string strictdateformatting can not be done because the string is not changed in AMOS. I think that the MOODLE_39_STABLE version is not uploaded to the Moodle plugin database.

<img width="1319" alt="moodle-questionnaire-strings" src="https://user-images.githubusercontent.com/27956839/85918071-dc8f3c80-b85f-11ea-9ab0-6d3c4171c0c3.png">

<img width="996" alt="moodle-questionnaire-amos" src="https://user-images.githubusercontent.com/27956839/85918097-08aabd80-b860-11ea-9146-988028a11828.png">

**Comment by mchurchward** [comment] 2020-06-29 13:45
Okay. I'm glad its working. It has not been released yet, but should be released this week.
